# Backend Dockerfile
FROM node:18-alpine

WORKDIR /app

# Install OpenSSL for Prisma
RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install

COPY . .
RUN chmod +x start.sh
RUN npx prisma generate
RUN npm run build

EXPOSE 5000

CMD ["./start.sh"]
